// get all contacts
GET http://localhost:3000

### // get contact by id
GET http://localhost:3000/contacts/626ab75a6d3ffdff8b4cb4a6

### create contact
POST http://localhost:3000/contacts 
//HTTP/1.1 
content-type:application/json

{
"firstName": "Charlie", "lastName": "Brown", "email":"cBrown@email.com", "favoriteColor":"Brown", "birthday":"08/19/2007"
}

### PUT contact/ change it
PUT http://localhost:3000/contacts/626ab75a6d3ffdff8b4cb4a6 
// HTTP/1.1 
content-type:application/json

{
"firstName":"Dave", "lastName":"Farrier", "email":"davef@email.com", "favoriteColor":"Brown", "birthday":"04/03/2000"
}

### delete contact
DELETE http://localhost:3000/contacts/62729f54607b3826fadefe68